#!/bin/bash
R="\033[1;31m"
RF="\033[31m"
V="\033[1;32m"
VF="\033[32m"
J="\033[1;33m"
JF="\033[33m"
C="\033[1;34m"
CF="\033[34m"
VI="\033[1;35m"
VIF="\033[35m"
B="\033[1;36m"
BF="\033[36m"
END="\033[0m"

echo -e "$V __     __   ____  _  _  _  _   __   ____                                              
(  )   / _\ (__  )( \/ )( \/ ) / _\ (  _ \                                      
/ (_/\/    \ / _/  )  / / \/ \/    \ ) __/                                          
\____/\_/\_/(____)(__/  \_)(_/\_/\_/(__)                            
$END"

echo -e "$C [1] Simple Scan (Default Scan) $END"
echo -e "$C [2] Medium Scan (Fast Port scan, TCP SYN/Connect) $END"
echo -e "$C [3] Complex Scan (Port Scan, OS indentification, Traceroute) $END"
echo -e -n "$V [*] Option Séléctioner: $END";
read;
if [ $REPLY = "1" ];then
Choix=1
elif [ $REPLY = "2" ];then
Choix=2
elif [ $REPLY = "3" ];then
Choix=3
else
echo -e "$R [!] Erreur syntax ou choix impossible $END"
fi
echo -e -n "$V [*] IP / Host: $END";
read;
HOST=$REPLY
if [ $Choix = "1" ];then
sudo nmap -sC $HOST
elif [ $Choix = "2" ];then
sudo nmap -sC -sS -sV $HOST
elif [ $Choix = "3" ];then
sudo nmap -sC -sS -sV -O --traceroute $HOST
fi
